// Writes src/index/dotnet-table.ts from the JSON the C# program in this folder prints:
//   dotnet run -c Release --project scripts/dotnet-table | tail -1 > /tmp/dotnet-members.json
//   node scripts/dotnet-table/emit.mjs /tmp/dotnet-members.json
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
const data = JSON.parse(readFileSync(process.argv[2], "utf8"));
const list = (names) => JSON.stringify(names.join(" "));
const lines = [
  "// Generated by scripts/dotnet-table/emit.mjs from .NET " + data.runtime + " reflection; do not edit by hand.",
  "// The public member names member lookup finds on each listed .NET type (methods, properties, fields and events,",
  "// inherited ones included), the extension method names each namespace's static classes declare, and each namespace's",
  "// top-level types: name with generic arity, kind (c class, C sealed class, s struct, r ref struct, e enum, i interface,",
  "// d delegate), + when the type declares an implicit conversion, and < its base class other than System.Object.",
  "",
  "export const DOTNET_RUNTIME = " + JSON.stringify(data.runtime) + ";",
  "",
  "const split = (names: string): ReadonlySet<string> => new Set(names.length === 0 ? [] : names.split(\" \"));",
  "",
  "export const DOTNET_MEMBERS: ReadonlyMap<string, ReadonlySet<string>> = new Map([",
  ...Object.entries(data.members).map(([type, names]) => `  [${JSON.stringify(type)}, split(${list(names)})],`),
  "]);",
  "",
  "export const DOTNET_EXTENSIONS: ReadonlyMap<string, ReadonlySet<string>> = new Map([",
  ...Object.entries(data.extensions).map(([ns, names]) => `  [${JSON.stringify(ns)}, split(${list(names)})],`),
  "]);",
  "",
  "export const DOTNET_TYPES: ReadonlyMap<string, string> = new Map([",
  ...Object.entries(data.kinds).map(([ns, entries]) => `  [${JSON.stringify(ns)}, ${list(entries)}],`),
  "]);",
  "",
];
writeFileSync(path.join(path.dirname(fileURLToPath(import.meta.url)), "../../src/index/dotnet-table.ts"), lines.join("\n"));
